### ISSUE TITLE
resurrect performance charts in summaries

### ISSUE THREAD

**Issue by justadreamer** [postindustria-tech/common-ci#3]
# Background
Something went wrong and now in device-detection-* repos we don't get performance charts published as part of the Nightly PRs to Main summary:
- https://github.com/51Degrees/device-detection-java/actions/runs/6634855486
- https://github.com/51Degrees/device-detection-cxx/actions/runs/6634317436

# Potential causes
Could be dealing with migration of hub -> gh cli tool.. 

# Objective
subj. please

**Comment by pi-alexander-popel** [comment]
The charts are fine:
https://github.com/51Degrees/device-detection-java/actions/runs/6634855486/attempts/1#summary-18025096561
https://github.com/51Degrees/device-detection-cxx/actions/runs/6634317436/attempts/1#summary-18024968877

The summaries started being sorted differently, so the charts don't auto-load now.
